version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: test
      DB_NAME: pos_db
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: pos_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
