name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Start services with docker-compose
        run: |
          docker compose -f docker-compose.yml up -d
          # Attendre que MySQL soit prêt
          echo "En attente du démarrage de MySQL..."
          docker compose -f docker-compose.yml exec -T db mysqladmin ping -uroot -ptest --wait=30 --silent
          echo "MySQL est prêt"

      - name: Check MySQL logs
        run: docker compose logs db

      - name: Verify MySQL
        run: |
          echo "Vérification des tables dans la base de données..."
          docker compose -f docker-compose.yml exec -T db mysql -uroot -ptest pos_db -e "SHOW TABLES;"
          echo "Vérification terminée"

      - name: Run tests
        run: npm test
        env:
          DB_HOST: db
          DB_USER: root
          DB_PASSWORD: test
          DB_NAME: pos_db
          DB_PORT: 3306

      - name: Stop services
        if: always()
        run: |
          docker compose -f docker-compose.yml down

      - name: Build application
        run: npm run build

      - name: Security audit
        run: npm audit || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t backproduct:latest .

      - name: Test with docker-compose
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 10
          curl --fail http://localhost:3000 || exit 1
          docker compose -f docker-compose.yml down
