name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Start services with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 20  # Attendre que MySQL et l'API démarrent (ajustez si nécessaire)

      - name: Verify MySQL
        run: |
          mysql -h localhost -u root -ptest pos_db -e "SHOW TABLES;"

      - name: Run tests
        run: npm test
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: test
          DB_NAME: pos_db
          DB_PORT: 3306

      - name: Stop services
        run: |
          docker-compose -f docker-compose.yml down

      - name: Build application
        run: npm run build

      - name: Security audit
        run: npm audit || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t backproduct:latest .

      - name: Test with docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 10
          curl --fail http://localhost:3000 || exit 1
          docker-compose -f docker-compose.yml down
